### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rawcomposition** [rawcomposition/birdinghotspots#1]
## Prototype

- [ ] Add Ohio header - https://vercel.com/docs/project-configuration#project-configuration/rewrites
- [ ] Verify that locationId still exists on ebird before adding/editing a hotspot
- [ ] Page meta Titles
- [ ] Add template for About section
- [ ] Link all ebird links to ebird portals if a portal exists
- [ ] Create custom error boundary to handle getServerSideProps errors
- [ ] Format HTML on copy and paste from old site
- [ ] Show "No results" on hotspot search if there's not results
- [ ] Handle image uploads

## Stage 2

**Drives List Page (include drives in Roadside Birding page)**

**Drives Detail Page**

**What's New Page**

**Contact Page**

**Search Page**

To Do

- [ ] Add top ebrid hotspots to state pages and counties using ebird API

## Notes

**Image Uploads**
Use Uppy, Transloadit, and Google Cloud Storage
Or resize using JS then upload directly to Google Cloud Storage 
https://stackoverflow.com/questions/37557343/resize-an-image-before-uploading-it-to-firebase
https://firebase.google.com/docs/storage/web/upload-files
FilePond: https://pqina.nl/filepond/docs/api/server/#advanced

**Routing Ohio domain**
https://stackoverflow.com/a/61267096/185885

# Nice to have

- [ ] Smooth scrolling for anchor links
- [ ] Clickable state maps don't work when scale down for mobile
- [ ] Find and replace abbreviations from Ken's spreadsheet
- [ ] Edit slug feature (only on update, not add)
- [ ] Debug why geocoding fails for Cuyahoga Valley NP--Virginia Kendall Lake and Trails
- [ ] Re-route old group hotspot links to new links
- [ ] Add county ebird reviewer names
- [ ] Standardize handling of state code. `US-` or no?
- [ ] Created at field
